### ISSUE TITLE
Consider replace golang.org/x/xerrors.Errorf with fmt.Errorf ？

### ISSUE THREAD

**Issue by simlecode** [whyrusleeping/cbor-gen#72]

**Comment by Stebalien** [comment]
We keep it for stack traces. See:

> Note that as of Go 1.13, the fmt.Errorf function will do error formatting, but it will not capture a stack backtrace. 

- https://pkg.go.dev/golang.org/x/xerrors#Errorf

**Comment by mvdan** [comment]
I'd personally revisit this. How badly are stack backtraces needed for all errors? The Go ecosystem moved away from xerrors years ago, so I doubt that the majority of cbor-gen users care about this feature - which has its cost too.

**Comment by Stebalien** [comment]
I still think xerrors has a place, but I agree that using xerrors in a _library_ like this has probably outlived its usefulness now that the community has moved on. Downstream users can still wrap errors with xerrors to get stack traces, they just won't get a stack trace through cbor-gen code (which they probably don't want anyways).

Thoughts @whyrusleeping?
