### ISSUE TITLE
use of internal package github.com/filecoin-project/venus/venus-shared/internal not allowed 

### ISSUE THREAD

**Issue by simlecode** [whyrusleeping/cbor-gen#74]
I found a error : `use of internal package github.com/filecoin-project/venus/venus-shared/internal not allowed`: https://github.com/filecoin-project/venus/blob/opt/generate_cbor_in_venus-devtool/pkg/fvm/cbor_gen.go#L11

**Comment by Stebalien** [comment]
This isn't a bug in this package, and there isn't enough information here to debug.
