### ISSUE TITLE
ScanForLinks brakes on empty block

### ISSUE THREAD

**Issue by hsanjuan** [whyrusleeping/cbor-gen#82]
A 0-byte raw block causes ScanForLinks to return an EOF error, when it should really simply say "no links".

i.e. a block like this fails:

```
echo -n "" | ipfs add -q --cid-version=1 --raw-leaves --only-hash --hash=blake2b-256
```
(bafk2bzaceahfouoae3suhmxivmxlayez3kq5dzo7i53y654h7kvultprf7r2q).

**Comment by Stebalien** [comment]
Closing because this package only works on CBOR data. We shouldn't be calling `ScanForLinks` on raw blocks.


If there _are_ places we're calling this function on non cbor data, we should fix them.
