### ISSUE TITLE
support for `map[string]string`

### ISSUE THREAD

**Issue by bnewbold** [whyrusleeping/cbor-gen#87]
It's possible i'm confused, but it seems that cbor-gen doesn't work with most `map[string]*` types, notably `map[string]string`. I think the code basically supports maps from strings to structs or pointers to structs.

If it is easy to knock out at the same time, support for `map[string]int64` and `map[string]bool` would be great.

**Comment by Stebalien** [comment]
Fixed by merging #83.

**Comment by Stebalien** [comment]
Note, this only adds string support. I'd be happy to merge support for other types if you can make a PR, but I'd really like to do this without special-casing every type...
